### ISSUE TITLE
Main page of website

### ISSUE THREAD

**Issue by somya51p** [ROBOTICS-CLUB-IIITDMJ/ERS-frontend#10]
Its UI should be somewhat like this.
The main page should be inside the `Main` folder.
The color scheme should be the same.

![Screenshot from 2021-07-29 19-51-20](https://user-images.githubusercontent.com/64978837/127508993-f75462ab-2d1d-49db-a9aa-0159377d4748.png)

**Comment by masterchief164** [comment]
Working on it
