### ISSUE TITLE
Downloads section

### ISSUE THREAD

**Issue by somya51p** [ROBOTICS-CLUB-IIITDMJ/ERS-frontend#51]

**Comment by a-Cash-dixit** [comment]
working on it.

**Comment by a-Cash-dixit** [comment]
![2021-09-22](https://user-images.githubusercontent.com/83697333/134320942-cc5eeb1c-3375-4e07-b0d1-2489e1925ebe.png)

How is that?

**Comment by somya51p** [comment]
Make the icons small....else its good

**Comment by a-Cash-dixit** [comment]
Ok

**Comment by a-Cash-dixit** [comment]
Now check the new PR

**Comment by a-Cash-dixit** [comment]
now check...
